#!/usr/bin/env bash
# Every declared @Database version has a committed schema JSON.
. "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"

meta() {
    ID="090-db-version-has-schema"
    TITLE="every @Database version has a committed schema"
    CATCHES="Bumping the Room schema version without committing the exported JSON.
Fails at RUNTIME on the emulator with

  FileNotFoundException: Cannot find the schema file in the assets folder

which reads like a broken test and is a missing file.

Committing matters because a clean CI checkout has no app/schemas/, and the
androidTest asset merge does not wait for KSP to write it. Putting the directory on
the asset path is necessary and NOT sufficient.

This is the first check in this corpus demoted from the emulator rung: it cost a
12-minute emulator round trip to discover and now costs two seconds.

ALSO catches the HISTORICAL schemas going missing, which is a quieter failure. A
Migration from version 1 to 2 needs 1.json to be testable, and nothing in the build
regenerates it -- a local KSP run emits only the CURRENT version. Clearing
app/schemas/ therefore destroys every earlier schema silently: the build stays
green, the migration tests stop proving anything, and git is the only copy left."
    SCOPE="any"
}
meta
ROOT="$(af_root "${1:-}")"

mapfile -t SRC < <(af_src_dirs "$ROOT")
[ ${#SRC[@]} -gt 0 ] || { pass "$TITLE (no sources)"; af_exit; }

mapfile -t DBFILES < <(grep -rlE '@Database\b' "${SRC[@]}" 2>/dev/null)
[ ${#DBFILES[@]} -gt 0 ] || { pass "$TITLE (no Room database)"; af_exit; }

# @Database(...) routinely spans lines, so slurp rather than grep.
versions=$(perl -0777 -ne '
    while (/\@Database\s*\((.*?)\)/gs) {
        my $b = $1;
        print "$1\n" if $b =~ /version\s*=\s*(\d+)/;
    }
' "${DBFILES[@]}" 2>/dev/null | sort -u)

[ -n "$versions" ] || { pass "$TITLE (no version declared)"; af_exit; }

# exportSchema=false is a deliberate choice to have no schemas; respect it.
if grep -rqE 'exportSchema\s*=\s*false' "${DBFILES[@]}" 2>/dev/null; then
    pass "$TITLE (exportSchema = false)"
    af_exit
fi

ok=1
for v in $versions; do
    if ! find "$ROOT/app/schemas" -name "$v.json" 2>/dev/null | grep -q .; then
        fail "@Database declares version $v but no committed app/schemas/**/$v.json exists"
        ok=0
    fi
done

# ── Every version a MIGRATION needs, not only the current one ───────────────
#
# The loop above asks only about the DECLARED version, and that is not enough.
# MigrationTestHelper opens the schema for the version it migrates FROM as well as
# the one it migrates TO, so a database at version 4 with three migrations needs
# 1, 2, 3 and 4 -- and the first version of this check passed with only 4.json.
#
# THE INCIDENT. `app/schemas/` was cleared and regenerated by a local KSP run, to
# confirm the schema could be produced without pushing. It could. What came back was
# `4.json` and nothing else: a schema records what the database looked like at a
# version, and nothing in the build remembers a version that is no longer declared.
# 1, 2 and 3 were gone. Nothing failed -- not the build, not the tests, not this
# check -- and the only surviving copy was in git.
#
# So the historical schemas are SOURCE, not build output, and this is the check that
# says so.
#
# Keyed on migrations rather than on "1..N must all exist", deliberately. A project
# that enabled exportSchema at version 3 legitimately has no 1.json or 2.json, and a
# 1..N rule would cry wolf at it forever. If that project also carries a migration
# from version 1, then that migration genuinely is untestable and saying so is
# correct. Narrow and correct beats general and noisy -- see check 050, which had to
# be rewritten for exactly this mistake.
mapfile -t MIGFILES < <(grep -rlE 'Migration\s*\(' "${SRC[@]}" 2>/dev/null)
if [ ${#MIGFILES[@]} -gt 0 ]; then
    # Both spellings Room offers: `Migration(1, 2)` is positional, the AutoMigration
    # annotation is named. The negative lookbehind keeps the first pattern off
    # `AutoMigration(`, and `from` is not a digit so it could not match anyway --
    # belt and braces, because this is the kind of pattern that is "nearly right".
    needed=$(perl -0777 -ne '
        while (/(?<!Auto)Migration\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gs) { print "$1\n$2\n"; }
        while (/AutoMigration\s*\(\s*from\s*=\s*(\d+)\s*,\s*to\s*=\s*(\d+)/gs) { print "$1\n$2\n"; }
    ' "${MIGFILES[@]}" 2>/dev/null | sort -un)

    for v in $needed; do
        # Already reported by the loop above; do not say it twice.
        printf '%s\n' $versions | grep -qx "$v" && continue
        if ! find "$ROOT/app/schemas" -name "$v.json" 2>/dev/null | grep -q .; then
            fail "a Migration references version $v but app/schemas/**/$v.json is absent -- that migration cannot be tested, and the schema is recoverable only from git"
            ok=0
        fi
    done
fi

[ "$ok" -eq 1 ] && pass "$TITLE ($(echo $versions | tr '\n' ' '))"
af_exit
